### ISSUE TITLE
Support for python3

### ISSUE THREAD

**Issue by ralphlauran99** [RafaelMarinheiro/RotationAveraging#1]
Hi, 
Thank you for writing this code, It works perfectly for python2, I was attempting to install it for python3, although it compiles and installs everything, python3 is unable to import algorithms.

```
>>> import rotation_averaging
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darkmatter/.local/lib/python3.6/site-packages/rotation_averaging/__init__.py", line 8, in <module>
    import algorithms
ModuleNotFoundError: No module named 'algorithms'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/darkmatter/.local/lib/python3.6/site-packages/rotation_averaging/__init__.py", line 8, in <module>
    import algorithms
ModuleNotFoundError: No module named 'algorithms'

```
All folders seem to be present inside rotation_averaging and yet it's unable to find algorithms 

```
darkmatter@ubuntu:~/.local/lib/python3.6/site-packages/rotation_averaging$ ls
algorithms  graph.py     minimization  rotation_averaging.py  util.py
compare.py  __init__.py  __pycache__   so3.py
```
```

darkmatter@ubuntu:~/.local/lib/python3.6/site-packages/rotation_averaging/algorithms$ ls
common.py  __init__.py  IRLS.py  L1RA.py  __pycache__

```
Greatly appreciate any help

**Comment by ralphlauran99** [comment]
I solved it by making the changes along these lines : 
instead of
 
import algorithms
import graph
import so3
import compare
import util

write : 

from rotation_averaging import algorithms
from rotation_averaging import graph
from rotation_averaging import so3
from rotation_averaging import compare
from rotation_averaging import util
